# We manually determined and selected matching points by obtaining their coordinates from Google Paint. In this process, we carefully identified and recorded the coordinates of 16 points to create a set of matching points.

In [12]:
import numpy as np

# Load the .npy file
file_path = 'right.npy'
array_data = np.load(file_path)

# Change the first entry to [500, 499, 1]
new_value = np.array([529, 194, 1])
array_data[0] = new_value
new_value = np.array([985, 96, 1])
array_data[1] = new_value
new_value = np.array([1435, 201, 1])
array_data[2] = new_value
new_value = np.array([1413, 790, 1])
array_data[3] = new_value
new_value = np.array([969, 988, 1])
array_data[4] = new_value
new_value = np.array([969, 320, 1])
array_data[5] = new_value
new_value = np.array([547, 780, 1])
array_data[6] = new_value
new_value = np.array([661, 444, 1])
array_data[7] = new_value
new_value = np.array([801, 492, 1])
array_data[8] = new_value
new_value = np.array([807, 716, 1])
array_data[9] = new_value
new_value = np.array([667, 652, 1])
array_data[10] = new_value
new_value = np.array([1137, 508, 1])
array_data[11] = new_value
new_value = np.array([1299, 452, 1])
array_data[12] = new_value
new_value = np.array([1293, 662, 1])
array_data[13] = new_value
new_value = np.array([1139, 720, 1])
array_data[14] = new_value
new_value = np.array([979, 226, 1])
array_data[15] = new_value
# Save the modified array back to the .npy file
np.save(file_path, array_data)
# Print or inspect the array data
print("Array data:")
print(array_data)

Array data:
[[ 529  194    1]
 [ 985   96    1]
 [1435  201    1]
 [1413  790    1]
 [ 969  988    1]
 [ 969  320    1]
 [ 547  780    1]
 [ 661  444    1]
 [ 801  492    1]
 [ 807  716    1]
 [ 667  652    1]
 [1137  508    1]
 [1299  452    1]
 [1293  662    1]
 [1139  720    1]
 [ 979  226    1]]


In [14]:
import numpy as np

# Load the .npy file
file_path = 'left.npy'
array_data = np.load(file_path)

# Change the first entry to [500, 499, 1]
new_value = np.array([1390, 194, 1])
array_data[0] = new_value
new_value = np.array([928, 96, 1])
array_data[1] = new_value
new_value = np.array([482, 201, 1])
array_data[2] = new_value
new_value = np.array([504, 790, 1])
array_data[3] = new_value
new_value = np.array([950, 988, 1])
array_data[4] = new_value
new_value = np.array([950, 320, 1])
array_data[5] = new_value
new_value = np.array([1370, 780, 1])
array_data[6] = new_value
new_value = np.array([1260, 444, 1])
array_data[7] = new_value
new_value = np.array([1114, 492, 1])
array_data[8] = new_value
new_value = np.array([1110, 716, 1])
array_data[9] = new_value
new_value = np.array([1250, 652, 1])
array_data[10] = new_value
new_value = np.array([776, 508, 1])
array_data[11] = new_value
new_value = np.array([624, 452, 1])
array_data[12] = new_value
new_value = np.array([626, 662, 1])
array_data[13] = new_value
new_value = np.array([780, 720, 1])
array_data[14] = new_value
new_value = np.array([936, 226, 1])
array_data[15] = new_value
# Save the modified array back to the .npy file
np.save(file_path, array_data)
# Print or inspect the array data
print("Array data:")
print(array_data)

Array data:
[[1390  194    1]
 [ 928   96    1]
 [ 482  201    1]
 [ 504  790    1]
 [ 950  988    1]
 [ 950  320    1]
 [1370  780    1]
 [1260  444    1]
 [1114  492    1]
 [1110  716    1]
 [1250  652    1]
 [ 776  508    1]
 [ 624  452    1]
 [ 626  662    1]
 [ 780  720    1]
 [ 936  226    1]]
